groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        # Condition for alerting
        expr: up == 0
        for: 1m
        # Annotation - additional informational labels to store more information
        annotations:
          title: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
        # Labels - additional labels to be attached to the alert
        labels:
          severity: "critical"
  - name: DiskSpaceOver75
    rules:
      - alert: "Disk space > 75% Full on Instance"
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"})  > 75
        for: 1m
        annotations:
          title: "Disk space over 75% on Instance {{ $labels.instance }}"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
        labels:
          severity: "critical"
